<a href="https://colab.research.google.com/github/HTKhuongNinh-FPTU/DS-AI-Project/blob/main/DataProcess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tập dữ liệu của dự án này chỉ lấy dữ liệu của thành phố có ID 03 từ tập dữ liệu train 4.5M rows. Vì dữ liệu tổng quá lớn nên chỉ thực hiện ở 1 quy mô dữ liệu nhỏ hơn.

**PHASE 1 (DATA INGESTION & OVERVIEW)**

In [ ]:
from datasets import load_dataset
import pandas as pd

# 1. Tải dataset
print("Đang tải dữ liệu về máy...")
dataset = load_dataset("Dingdong-Inc/FreshRetailNet-50K", split='train')
# 2. Lọc dữ liệu bằng bộ lọc của dataset
print("Đang lọc City ID 3...")
df_city_3 = dataset.filter(lambda example: example['city_id'] == 3)
print(f"Đã hoàn thành! Có {len(df_city_3)} dòng dữ liệu cho City ID 3.")

Overview

In [10]:
# Check the downloaded dataset information
print("\nDataset Information:")
print(df_city_3)

# Convert to Pandas DataFrame for data processing
print("\nConverting to Pandas DataFrame...")
df_city_3 = pd.DataFrame(df_city_3)

# Check size and preview data
print(f"Dataset size: {df_city_3.shape}")
df_city_3.head()

Dataset Information:
         store_id   product_id          dt  sale_amount  \
0        Store_70  Product_157  2024-03-28         1.80
1        Store_70  Product_157  2024-03-29         1.50
2        Store_70  Product_157  2024-03-30         1.80
3        Store_70  Product_157  2024-03-31         1.78
4        Store_70  Product_157  2024-04-01         1.80
...           ...          ...         ...          ...
238315  Store_889  Product_666  2024-06-21         1.10
238316  Store_889  Product_666  2024-06-22         1.20
238317  Store_889  Product_666  2024-06-23         1.20
238318  Store_889  Product_666  2024-06-24         1.00
238319  Store_889  Product_666  2024-06-25         1.00

                                               hours_sale  stock_hour6_22_cnt  \
0       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.7, 1.1, 0.0, ...                  15
1       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, ...                   9
2       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6, 0.0, 0.6, ...                  11
3       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6, 0.0, ...                   3
4       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0, ...                   9
...                                                   ...                 ...
238315  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...                   0
238316  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.1, ...                   9
238317  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...                   6
238318  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, ...                   0
238319  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, ...                   0

                                       hours_stock_status  discount  \
0       [1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, ...     0.914
1       [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, ...     0.897
2       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, ...     0.897
3       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...     0.903
4       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, ...     0.897
...                                                   ...       ...
238315  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...     0.869
238316  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, ...     0.869
238317  [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...     0.869
238318  [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...     0.869
238319  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...     0.869

        holiday_flag  activity_flag  precpt  avg_temperature  avg_humidity  \
0                  0              0  0.0142            14.32         31.25
1                  0              0  0.4079            14.60         29.95
2                  1              0  0.6128            14.68         31.86
3                  1              0  0.3063            16.94         35.42
4                  0              0  0.7007            16.21         39.26
...              ...            ...     ...              ...           ...
238315             0              1  1.3534            28.65         50.81
238316             1              1  1.0314            28.51         48.01
238317             1              1  0.7480            28.08         47.08
238318             0              1  1.0061            29.40         50.07
238319             0              1  2.2713            29.17         50.74

        avg_wind_level
0                 1.57
1                 1.57
2                 1.34
3                 1.38
4                 1.23
...                ...
238315            1.80
238316            1.34
238317            1.25
238318            1.32
238319            1.48

[238320 rows x 14 columns]

Converting to Pandas DataFrame...
Dataset size: (238320, 14)

,store_id,product_id,dt,sale_amount,hours_sale,stock_hour6_22_cnt,hours_stock_status,discount,holiday_flag,activity_flag,precpt,avg_temperature,avg_humidity,avg_wind_level
0,Store_70,Product_157,2024-03-28,1.80,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.7, 1.1, 0.0, ...",15,"[1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, ...",0.914,0,0,0.0142,14.32,31.25,1.57
1,Store_70,Product_157,2024-03-29,1.50,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, ...",9,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, ...",0.897,0,0,0.4079,14.60,29.95,1.57
2,Store_70,Product_157,2024-03-30,1.80,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6, 0.0, 0.6, ...",11,"[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, ...",0.897,1,0,0.6128,14.68,31.86,1.34
3,Store_70,Product_157,2024-03-31,1.78,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6, 0.0, ...",3,"[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.903,1,0,0.3063,16.94,35.42,1.38
4,Store_70,Product_157,2024-04-01,1.80,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0, ...",9,"[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, ...",0.897,0,0,0.7007,16.21,39.26,1.23

**PHASE 2 (DATA SELECTION)**

Loại bỏ bớt các đặc tính không hữu ích

In [11]:
columns_to_drop = ['management_group_id', 'first_category_id', 'second_category_id', 'third_category_id', 'city_id']
df_city_3 = df_city_3.drop(columns=columns_to_drop, errors='ignore')
print(f"Dropped columns: {columns_to_drop}")
print(f"New DataFrame shape: {df_city_3.shape}")

Dropped columns: ['management_group_id', 'first_category_id', 'second_category_id', 'third_category_id', 'city_id']
New DataFrame shape: (238320, 14)

**PHASE 3 (DATA CLEANING)**

Data Validation

In [12]:
print("Checking for Missing Values:")
missing_values = df_city_3.isnull().sum()
missing_percentage = (df_city_3.isnull().sum() / len(df_city_3)) * 100
missing_df = pd.DataFrame({'Missing Count': missing_values, 'Missing Percentage': missing_percentage})
print(missing_df[missing_df['Missing Count'] > 0])
if missing_df[missing_df['Missing Count'] > 0].empty:
    print("No missing values found.\n")
else:
    print("\nColumns with missing values found. Consider imputation or removal.\n")

print("Checking for Duplicate Rows:")
list_cols = [col for col in df_city_3.columns if isinstance(df_city_3[col].iloc[0], list) or isinstance(df_city_3[col].iloc[0], tuple)]

subset_cols_for_duplicate_check = [col for col in df_city_3.columns if col not in list_cols]
duplicate_rows = df_city_3.duplicated(subset=subset_cols_for_duplicate_check).sum()
if duplicate_rows == 0:
    print("No duplicate rows found (excluding list-type columns).\n")
else:
    print(f"Found {duplicate_rows} duplicate rows (excluding list-type columns). Consider removing them.\n")

print("Checking Data Types and Info:")
df_city_3.info()

Checking for Missing Values:
Empty DataFrame
Columns: [Missing Count, Missing Percentage]
Index: []
No missing values found.

Checking for Duplicate Rows:
No duplicate rows found (excluding list-type columns).

Checking Data Types and Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238320 entries, 0 to 238319
Data columns (total 14 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   store_id            238320 non-null  object
 1   product_id          238320 non-null  object
 2   dt                  238320 non-null  object
 3   sale_amount         238320 non-null  float64
 4   hours_sale          238320 non-null  object
 5   stock_hour6_22_cnt  238320 non-null  int64
 6   hours_stock_status  238320 non-null  object
 7   discount            238320 non-null  float64
 8   holiday_flag        238320 non-null  int64
 9   activity_flag       238320 non-null  int64
 10  precpt              238320 non-null  float64
 11  avg_temperature     238320 non-null  float64
 12  avg_humidity        238320 non-null  float64
 13  avg_wind_level      238320 non-null  float64
dtypes: float64(6), int64(3), object(5)
memory usage: 25.5+ MB

Data Transformation

In [13]:
df_city_3['store_id'] = 'Store_' + df_city_3['store_id'].astype(str)
df_city_3['product_id'] = 'Product_' + df_city_3['product_id'].astype(str)
print(df_city_3[['store_id', 'product_id']].head())

         store_id           product_id
0  Store_Store_70  Product_Product_157
1  Store_Store_70  Product_Product_157
2  Store_Store_70  Product_Product_157
3  Store_Store_70  Product_Product_157
4  Store_Store_70  Product_Product_157

Re-checking

In [14]:
df_city_3.head()

,store_id,product_id,dt,sale_amount,hours_sale,stock_hour6_22_cnt,hours_stock_status,discount,holiday_flag,activity_flag,precpt,avg_temperature,avg_humidity,avg_wind_level
0,Store_Store_70,Product_Product_157,2024-03-28,1.80,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.7, 1.1, 0.0, ...",15,"[1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, ...",0.914,0,0,0.0142,14.32,31.25,1.57
1,Store_Store_70,Product_Product_157,2024-03-29,1.50,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, ...",9,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, ...",0.897,0,0,0.4079,14.60,29.95,1.57
2,Store_Store_70,Product_Product_157,2024-03-30,1.80,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6, 0.0, 0.6, ...",11,"[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, ...",0.897,1,0,0.6128,14.68,31.86,1.34
3,Store_Store_70,Product_Product_157,2024-03-31,1.78,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6, 0.0, ...",3,"[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.903,1,0,0.3063,16.94,35.42,1.38
4,Store_Store_70,Product_Product_157,2024-04-01,1.80,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0, ...",9,"[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, ...",0.897,0,0,0.7007,16.21,39.26,1.23

Create file

In [15]:
output_filename = "freshretailnet_city_03_dataset.csv"
df_city_3.to_csv(output_filename, index=False)
print(f"DataFrame saved to {output_filename}")

DataFrame saved to freshretailnet_city_03_dataset.csv

END